### ISSUE TITLE
Program returns only a single file's average

### ISSUE THREAD

**Issue by SoloSynth1** [SoloSynth1/harri20181020#1]
To quote Harris:

"We shd have the average first before having the chosen kne
For now we have the chosen one first before the average
The outcome is average of the chosen one file only
Instead of average of all files"

Amen.

**Comment by SoloSynth1** [comment]
@harrywhoforks please push the quickfix and create a pull request.

**Comment by SoloSynth1** [comment]
@harrywhoforks  please pull the latest commit 6beb7ad06ea2b801ca8088ef0f57b3838dffe331, I have pushed it to remove the outdated main.exe.

**Comment by harrywhoforks** [comment]
I have pushed a new branch ava_csv_v2 and create a pull request.
Btw, I tried to make the .exe for the code but its size was so big since I believe i cant create virtual env with Spyder.....

**Comment by SoloSynth1** [comment]
> I have pushed a new branch ava_csv_v2 and create a pull request.
> Btw, I tried to make the .exe for the code but its size was so big since I believe i cant create virtual env with Spyder.....

I can see you have created a new branch; but I can't see any changes in your ```main.py```. Maybe you forgot to commit and push the changes?

**Comment by SoloSynth1** [comment]
> I have pushed a new branch ava_csv_v2 and create a pull request.
> Btw, I tried to make the .exe for the code but its size was so big since I believe i cant create virtual env with Spyder.....

Actually you can create a new venv manually, create a new folder to store the virtual environment, then `python -m venv /your/path/to/venv`, you can activate the venv by running `source /your/path/to/venv/bin/activate`. If you are using Windows, replace `bin` with `Scripts` would do.

**Comment by harrywhoforks** [comment]
Just now, I tried to use pyCharm in my notebook for trying to convert the .py to .exe with PyInstaller. I created a new venv and added Pyinstaller and Numpy. Then I run Pyinstaller in the terminal of pyCharm and it successfully created a .exe file but just doesnt work. Not sure why....sosad

**Comment by harrywhoforks** [comment]
ok problem solved. it was numpy version issue that made the .exe didnt work.

**Comment by SoloSynth1** [comment]
> ok problem solved. it was numpy version issue that made the .exe didnt work.

did you install the numpy package by using ```pip install -r requirements.txt```?

**Comment by harrywhoforks** [comment]
> > ok problem solved. it was numpy version issue that made the .exe didnt work.
> 
> did you install the numpy package by using `pip install -r requirements.txt`?

I checked the numpy version in requirements.txt and reinstall the numpy with older version. Your way is definitely better lol

**Comment by SoloSynth1** [comment]
> > > ok problem solved. it was numpy version issue that made the .exe didnt work.
> > 
> > 
> > did you install the numpy package by using `pip install -r requirements.txt`?
> 
> I checked the numpy version in requirements.txt and reinstall the numpy with older version. Your way is definitely better lol

I learnt this the hard way lol

**Comment by SoloSynth1** [comment]
The latest pull request from ```ava_csv_test``` to ```ava_csv``` addressed this issue. Closing the issue now.
